---
- name: Install the datadog apt key
  apt_key: id=C7A7DA52 keyserver=keyserver.ubuntu.com state=present

- name: Install the apt repo for datadog
  apt_repository: repo='deb http://apt.datadoghq.com/ stable main' state=present update_cache=yes

- name: Apt install datadog
  apt: name=datadog-agent state=latest

- name: Install datadog apt dependencies
  apt: name="{{item}}"
  with_items: datadog_apt_packages


