---

# service datadog-agent restart may not release collector
- name: restart dd-agent
  shell: dd-agent stop
  changed_when: true
  notify: stop all the processes running as dd-agent user

- name: stop all the processes running as dd-agent user 
  service:
   name: datadog-agent
   state: stopped
  changed_when: true
  notify: remove the /tmp/dd-agent.pid file

- name: remove the /tmp/dd-agent.pid file 
  file: 
   state: absent
   dest: /tmp/dd-agent.pid
  changed_when: true
  notify: fix up the ownership on /var/log/datadog dir

- name: fix up the ownership on /var/log/datadog dir
  file:
   state: directory
   owner: "dd-agent"
   dest: /var/log/datadog
   recurse: yes
  changed_when: true
  notify: kill all the zombie processes running as dd-agent user

- name: kill all the zombie processes running as dd-agent user 
  shell: kill -9 $(pgrep datadog)
  changed_when: true
  ignore_errors: yes
  notify: kill the rest of the zombies

- name: kill the rest of the zombies
  shell: kill -9 $(ps aux|grep [d]atadog | tr -s ' ' | cut -f2 -d' ')
  changed_when: true
  ignore_errors: yes
  notify: restart datadog-agent service

- name: restart datadog-agent service
  service: name=datadog-agent state=restarted


